# name=FL Slacker (metadata)
# url=

"""device_Slacker - FL Slacker adapter (protocol flslacker/1, package 0.1.0).

Optional read-only MIDI metadata adapter.

GENERATED by `flslacker build-fl-scripts` from src/flslacker; do not edit by hand.
"""


# -------------------- inlined: flslacker/contracts/canonical.py --------------------

"""Canonical JSON, hashing and FL note records for protocol ``flslacker/1``.

STDLIB ONLY. This module is inlined verbatim into the FL-side Piano Roll scripts
(see ``flslacker.fl_build``), so it must run on FL's embedded interpreter without
companion dependencies. Lines ending in ``# fl-inline: skip`` are dropped when inlined.

Canonicalization (version 1), also published in docs/SPEC.md:

* JSON text with keys sorted, separators ``,`` and ``:``, ASCII-only escapes,
  UTF-8 bytes, no insignificant whitespace.
* Integers are written in decimal. ``bool`` is never treated as an integer.
* Floats are written with Python's shortest round-trip ``repr``; ``-0.0`` becomes
  ``0.0``; NaN and infinities are rejected.
* Lists keep their order. Dictionary keys must be strings.
* A hash is the lowercase hex SHA-256 of the canonical bytes.
"""

import hashlib
import hmac
import json
import math

PROTOCOL = "flslacker/1"
CANON_VERSION = 1

# FL-native Note attributes, in canonical order, with the Python type FL is documented to return.
NOTE_FIELDS = (
    ("number", "int"),
    ("time", "int"),
    ("length", "int"),
    ("group", "int"),
    ("pan", "float"),
    ("velocity", "float"),
    ("release", "float"),
    ("color", "int"),
    ("fcut", "float"),
    ("fres", "float"),
    ("pitchofs", "int"),
    ("slide", "bool"),
    ("porta", "bool"),
    ("muted", "bool"),
    ("selected", "bool"),
    ("repeats", "int"),
)
NOTE_FIELD_NAMES = tuple(name for name, _ in NOTE_FIELDS)
NOTE_FIELD_TYPES = dict(NOTE_FIELDS)

MARKER_FIELDS = (
    ("time", "int"),
    ("name", "str"),
    ("mode", "int"),
    ("tsnum", "int"),
    ("tsden", "int"),
)
MARKER_FIELD_NAMES = tuple(name for name, _ in MARKER_FIELDS)

# Fields the baseline writer may set, with inclusive bounds (None = boolean).
WRITABLE_NOTE_FIELDS = {
    "number": (0, 127),
    "time": (0, 2**31 - 1),
    "length": (1, 2**31 - 1),
    "group": (0, 2**31 - 1),
    "pan": (0.0, 1.0),
    "velocity": (0.0, 1.0),
    "release": (0.0, 1.0),
    "color": (0, 15),
    "fcut": (0.0, 1.0),
    "fres": (0.0, 1.0),
    "pitchofs": (-120, 120),
    "slide": None,
    "porta": None,
    "muted": None,
    "selected": None,
    "repeats": (0, 14),
}
# Fields an update may change. `group` and `selected` are only written on insert.
UPDATABLE_NOTE_FIELDS = tuple(
    name for name in NOTE_FIELD_NAMES if name not in ("group", "selected")
)

# Tolerance for comparing float properties after a write; FL stores several of them quantized.
FLOAT_TOLERANCE = 0.01

# Fields ignored when comparing musical content (selection is UI state).
CONTENT_IGNORED_FIELDS = ("selected",)


class CanonicalError(ValueError):
    pass


def _normalize(value):
    if value is None or isinstance(value, (bool, str)):
        return value
    if isinstance(value, int):
        return int(value)
    if isinstance(value, float):
        if not math.isfinite(value):
            raise CanonicalError("non-finite float")
        if value == 0.0:
            return 0.0
        return value
    if isinstance(value, (list, tuple)):
        return [_normalize(item) for item in value]
    if isinstance(value, dict):
        out = {}
        for key, item in value.items():
            if not isinstance(key, str):
                raise CanonicalError("non-string key")
            out[key] = _normalize(item)
        return out
    raise CanonicalError("unsupported type: " + type(value).__name__)


def canonical_dumps(value):
    return json.dumps(
        _normalize(value),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
        allow_nan=False,
    )


def canonical_bytes(value):
    return canonical_dumps(value).encode("utf-8")


def sha256_hex(value):
    return hashlib.sha256(canonical_bytes(value)).hexdigest()


def hmac_hex(secret_hex, value):
    return hmac.new(bytes.fromhex(secret_hex), canonical_bytes(value), hashlib.sha256).hexdigest()


def hmac_matches(secret_hex, value, tag):
    if not isinstance(tag, str):
        return False
    return hmac.compare_digest(hmac_hex(secret_hex, value), tag)


# ---------------------------------------------------------------- records


def _coerce_read(kind, value):
    """Keep what FL returned, except for lossless int/bool normalisation."""
    if kind == "bool" and isinstance(value, int) and value in (0, 1):
        return bool(value)
    if kind == "int" and isinstance(value, bool):
        return int(value)
    if kind == "int" and isinstance(value, float) and value.is_integer():
        return int(value)
    return value


def read_record(obj, fields):
    """Read ``fields`` from an FL object. Returns (record, errors)."""
    record = {}
    errors = {}
    for name, kind in fields:
        try:
            value = _coerce_read(kind, getattr(obj, name))
            _normalize(value)
        except Exception as exc:  # FL raises for unsupported attributes
            errors[name] = type(exc).__name__ + ": " + str(exc)[:200]
            continue
        record[name] = value
    return record, errors


def read_note(note):
    return read_record(note, NOTE_FIELDS)


def read_marker(marker):
    return read_record(marker, MARKER_FIELDS)


def extra_attributes(obj, known):
    """Public, non-callable scalar attributes not in ``known`` (for compatibility reports)."""
    extras = {}
    for name in dir(obj):
        if name.startswith("_") or name in known:
            continue
        try:
            value = getattr(obj, name)
        except Exception:
            continue
        if callable(value):
            continue
        if isinstance(value, (bool, int, float, str)) or value is None:
            try:
                extras[name] = _normalize(value)
            except CanonicalError:
                extras[name] = repr(value)[:80]
    return extras


def note_fingerprint(record):
    return sha256_hex({"v": CANON_VERSION, "kind": "note", "record": record})


def state_hash(ppq, notes, markers):
    """Order-sensitive hash of the exposed score, used to detect any intervening change."""
    return sha256_hex(
        {"v": CANON_VERSION, "kind": "state", "ppq": ppq, "notes": list(notes), "markers": list(markers)}
    )


def _content_view(record):
    return {k: v for k, v in record.items() if k not in CONTENT_IGNORED_FIELDS}


def content_hash(ppq, notes, markers):
    """Order-independent hash of musical content (selection excluded)."""
    note_keys = sorted(canonical_dumps(_content_view(r)) for r in notes)
    marker_keys = sorted(canonical_dumps(m) for m in markers)
    return sha256_hex(
        {"v": CANON_VERSION, "kind": "content", "ppq": ppq, "notes": note_keys, "markers": marker_keys}
    )


# ---------------------------------------------------------------- validation


def check_note_value(field, value):
    """Return an error string, or None when ``value`` may be written to ``field``."""
    if field not in WRITABLE_NOTE_FIELDS:
        return "field not writable: " + str(field)
    bounds = WRITABLE_NOTE_FIELDS[field]
    kind = NOTE_FIELD_TYPES[field]
    if bounds is None:
        if not isinstance(value, bool):
            return field + " must be a boolean"
        return None
    if kind == "int":
        if isinstance(value, bool) or not isinstance(value, int):
            return field + " must be an integer"
    else:
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            return field + " must be a number"
        if not math.isfinite(float(value)):
            return field + " must be finite"
    if value < bounds[0] or value > bounds[1]:
        return "%s out of range [%s, %s]" % (field, bounds[0], bounds[1])
    return None


def validate_operations(records, operations):
    """Validate FL-native operations against live ``records``. Returns a list of errors."""
    errors = []
    touched = set()
    for index, op in enumerate(operations):
        kind = op.get("op")
        where = "operation %d" % index
        if kind in ("update", "delete"):
            ordinal = op.get("ordinal")
            if isinstance(ordinal, bool) or not isinstance(ordinal, int) or not 0 <= ordinal < len(records):
                errors.append(where + ": ordinal out of range")
                continue
            if ordinal in touched:
                errors.append(where + ": note targeted twice")
            touched.add(ordinal)
            if note_fingerprint(records[ordinal]) != op.get("fingerprint"):
                errors.append(where + ": note fingerprint does not match live note")
            if kind == "update":
                values = op.get("set")
                if not isinstance(values, dict) or not values:
                    errors.append(where + ": empty update")
                    continue
                for field, value in values.items():
                    if field not in UPDATABLE_NOTE_FIELDS:
                        errors.append(where + ": field not updatable: " + str(field))
                        continue
                    problem = check_note_value(field, value)
                    if problem:
                        errors.append(where + ": " + problem)
        elif kind == "insert":
            note = op.get("note")
            if not isinstance(note, dict) or set(note) != set(NOTE_FIELD_NAMES):
                errors.append(where + ": insert needs a complete note template")
                continue
            for field, value in note.items():
                problem = check_note_value(field, value)
                if problem:
                    errors.append(where + ": " + problem)
        else:
            errors.append(where + ": unknown op " + repr(kind)[:40])
    return errors


def predict_after(records, operations):
    """Apply FL-native operations to a copy of ``records`` (updates, deletes, then inserts)."""
    result = [dict(r) for r in records]
    for op in operations:
        if op["op"] == "update":
            result[op["ordinal"]].update(op["set"])
    for op in sorted((o for o in operations if o["op"] == "delete"), key=lambda o: o["ordinal"], reverse=True):
        del result[op["ordinal"]]
    for op in operations:
        if op["op"] == "insert":
            result.append(dict(op["note"]))
    return result


def _split_record(record):
    exact = {}
    floats = {}
    for key, value in _content_view(record).items():
        if isinstance(value, float):
            floats[key] = value
        else:
            exact[key] = value
    return canonical_dumps(exact), floats


def match_contents(expected, observed, tolerance=FLOAT_TOLERANCE, limit=20):
    """Compare two note multisets, ignoring order and selection, with float tolerance.

    Returns (ok, mismatches) where mismatches is a short list of human-readable strings.
    Float fields are compared with ``tolerance``; all other fields must match exactly, so
    callers must write float fields as floats.
    """
    mismatches = []

    def bucket(records):
        out = {}
        for record in records:
            exact_key, floats = _split_record(record)
            out.setdefault(exact_key, []).append(floats)
        return out

    want = bucket(expected)
    have = bucket(observed)
    for key in sorted(set(want) | set(have)):
        wanted = sorted(want.get(key, []), key=lambda f: sorted(f.items()))
        found = sorted(have.get(key, []), key=lambda f: sorted(f.items()))
        remaining = list(found)
        for floats in wanted:
            hit = None
            for position, candidate in enumerate(remaining):
                if set(candidate) == set(floats) and all(
                    abs(candidate[name] - floats[name]) <= tolerance for name in floats
                ):
                    hit = position
                    break
            if hit is None:
                if len(mismatches) < limit:
                    mismatches.append("missing note " + key + " " + canonical_dumps(floats))
            else:
                del remaining[hit]
        for floats in remaining:
            if len(mismatches) < limit:
                mismatches.append("unexpected note " + key + " " + canonical_dumps(floats))
        if remaining and len(mismatches) >= limit:
            break
    ok = not mismatches and len(expected) == len(observed)
    if not ok and not mismatches:
        mismatches.append("note count differs: expected %d, observed %d" % (len(expected), len(observed)))
    return ok, mismatches

# -------------------- inlined: flslacker/contracts/wire.py --------------------

"""Mailbox wire protocol: pairing, signed envelopes and atomic files.

STDLIB ONLY and inlined into the FL-side scripts together with ``canonical``.
Lines ending in ``# fl-inline: skip`` are dropped when inlined.

Layout below the per-user base directory (never a synchronized folder)::

    bridge/pairing.json                         session id + shared secret
    mailbox/sessions/<session_id>/requests/     companion -> FL (named <request_id>.json)
    mailbox/sessions/<session_id>/responses/    FL -> companion (random UUID names)
    mailbox/sessions/<session_id>/snapshots/    FL -> companion (random UUID names)
    mailbox/sessions/<session_id>/claims/       <request_id>.claim, created exclusively
"""

import calendar
import json
import os
import sys
import time
import uuid


MAX_MESSAGE_BYTES = 4 * 1024 * 1024
MAX_SNAPSHOT_NOTES = 10000
MAX_PATCH_OPERATIONS = 1000
CLOCK_SKEW_SECONDS = 300

ENVELOPE_FIELDS = (
    "protocol",
    "kind",
    "session_id",
    "request_id",
    "in_reply_to",
    "sequence",
    "sender",
    "created_at",
    "expires_at",
    "body",
    "auth",
)
# kind -> (sender, mailbox folder)
MESSAGE_KINDS = {
    "capture_request": ("companion", "requests"),
    "apply_request": ("companion", "requests"),
    "snapshot": ("fl", "snapshots"),
    "capture_error": ("fl", "responses"),
    "apply_response": ("fl", "responses"),
    "midi_status": ("fl", "responses"),
}
MAILBOX_FOLDERS = ("requests", "responses", "snapshots", "claims")


class BridgeError(Exception):
    pass


def utc_iso(epoch=None):
    if epoch is None:
        epoch = time.time()
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(int(epoch)))


def parse_utc_iso(text):
    if not isinstance(text, str):
        raise BridgeError("timestamp must be a string")
    try:
        return calendar.timegm(time.strptime(text, "%Y-%m-%dT%H:%M:%SZ"))
    except ValueError:
        raise BridgeError("bad timestamp")


def is_uuid(text):
    if not isinstance(text, str) or len(text) != 36:
        return False
    try:
        return str(uuid.UUID(text)) == text
    except ValueError:
        return False


def base_dir():
    override = os.environ.get("FLSLACKER_HOME")
    if override:
        return os.path.abspath(override)
    if os.name == "nt":
        root = os.environ.get("LOCALAPPDATA") or os.path.join(os.path.expanduser("~"), "AppData", "Local")
        return os.path.join(root, "FLSlacker")
    if sys.platform == "darwin":
        return os.path.join(os.path.expanduser("~"), "Library", "Application Support", "FLSlacker")
    root = os.environ.get("XDG_DATA_HOME") or os.path.join(os.path.expanduser("~"), ".local", "share")
    return os.path.join(root, "flslacker")


def pairing_path(base):
    return os.path.join(base, "bridge", "pairing.json")


def session_path(base, session_id):
    if not is_uuid(session_id):
        raise BridgeError("invalid session id")
    return os.path.join(base, "mailbox", "sessions", session_id)


def ensure_private_dir(path):
    os.makedirs(path, mode=0o700, exist_ok=True)
    return path


def atomic_write_text(directory, name, text):
    """Write ``text`` to ``directory/name`` via an exclusive temp file and rename."""
    if os.sep in name or (os.altsep and os.altsep in name) or name.startswith("."):
        raise BridgeError("invalid file name")
    data = text.encode("utf-8")
    if len(data) > MAX_MESSAGE_BYTES:
        raise BridgeError("message exceeds size limit")
    temp = os.path.join(directory, ".tmp-" + uuid.uuid4().hex)
    fd = os.open(temp, os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_BINARY", 0), 0o600)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temp, os.path.join(directory, name))
    except Exception:
        try:
            os.remove(temp)
        except OSError:
            pass
        raise
    return os.path.join(directory, name)


def _reject_constant(name):
    raise BridgeError("non-finite number in JSON")


def load_json_file(path, max_bytes=MAX_MESSAGE_BYTES):
    size = os.path.getsize(path)
    if size > max_bytes:
        raise BridgeError("file exceeds size limit")
    with open(path, "rb") as handle:
        data = handle.read(max_bytes + 1)
    if len(data) > max_bytes:
        raise BridgeError("file exceeds size limit")
    return json.loads(data.decode("utf-8"), parse_constant=_reject_constant)


def claim_path(session_dir, request_id):
    if not is_uuid(request_id):
        raise BridgeError("invalid request id")
    return os.path.join(session_dir, "claims", request_id + ".claim")


def try_claim(session_dir, request_id, holder):
    """Exclusively create the claim for ``request_id``. Returns False if already claimed."""
    path = claim_path(session_dir, request_id)
    try:
        fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_BINARY", 0), 0o600)
    except FileExistsError:
        return False
    with os.fdopen(fd, "wb") as handle:
        handle.write(holder.encode("utf-8")[:200])
        handle.flush()
        os.fsync(handle.fileno())
    return True


def read_claim(session_dir, request_id):
    path = claim_path(session_dir, request_id)
    try:
        with open(path, "rb") as handle:
            return handle.read(200).decode("utf-8", "replace")
    except FileNotFoundError:
        return None


def make_envelope(secret, kind, session_id, sequence, body, ttl_seconds, in_reply_to=None, request_id=None, now=None):
    if kind not in MESSAGE_KINDS:
        raise BridgeError("unknown message kind")
    if now is None:
        now = time.time()
    envelope = {
        "protocol": PROTOCOL,
        "kind": kind,
        "session_id": session_id,
        "request_id": request_id or str(uuid.uuid4()),
        "in_reply_to": in_reply_to,
        "sequence": int(sequence),
        "sender": MESSAGE_KINDS[kind][0],
        "created_at": utc_iso(now),
        "expires_at": utc_iso(now + ttl_seconds),
        "body": body,
    }
    envelope["auth"] = hmac_hex(secret, envelope)
    return envelope


def check_envelope(secret, envelope, session_id, kinds, now=None):
    """Return None if ``envelope`` is acceptable, otherwise a short reason string."""
    if now is None:
        now = time.time()
    if not isinstance(envelope, dict):
        return "not an object"
    if set(envelope) != set(ENVELOPE_FIELDS):
        return "unexpected or missing envelope fields"
    if envelope["protocol"] != PROTOCOL:
        return "unsupported protocol"
    if envelope["kind"] not in kinds or envelope["kind"] not in MESSAGE_KINDS:
        return "unexpected message kind"
    if envelope["sender"] != MESSAGE_KINDS[envelope["kind"]][0]:
        return "wrong sender"
    if envelope["session_id"] != session_id:
        return "wrong session"
    if not is_uuid(envelope["request_id"]):
        return "bad request id"
    if envelope["in_reply_to"] is not None and not is_uuid(envelope["in_reply_to"]):
        return "bad in_reply_to"
    sequence = envelope["sequence"]
    if isinstance(sequence, bool) or not isinstance(sequence, int) or sequence < 0:
        return "bad sequence"
    if not isinstance(envelope["body"], dict):
        return "bad body"
    try:
        created = parse_utc_iso(envelope["created_at"])
        expires = parse_utc_iso(envelope["expires_at"])
    except BridgeError:
        return "bad timestamp"
    if created > now + CLOCK_SKEW_SECONDS:
        return "created in the future"
    if expires < now:
        return "expired"
    unsigned = dict(envelope)
    tag = unsigned.pop("auth")
    if not hmac_matches(secret, unsigned, tag):
        return "bad authentication tag"
    return None


def read_pairing(base):
    path = pairing_path(base)
    if not os.path.exists(path):
        raise BridgeError(
            "FL Slacker companion is not paired. Start it with `flslacker serve` and try again."
        )
    try:
        pairing = load_json_file(path, 64 * 1024)
    except (OSError, ValueError, BridgeError) as exc:
        raise BridgeError("pairing file is unreadable: " + str(exc)[:120])
    if not isinstance(pairing, dict) or pairing.get("protocol") != PROTOCOL:
        raise BridgeError("pairing file has an unsupported protocol version")
    secret = pairing.get("secret")
    if not is_uuid(pairing.get("session_id")) or not isinstance(secret, str) or len(secret) != 64:
        raise BridgeError("pairing file is malformed")
    try:
        bytes.fromhex(secret)
    except ValueError:
        raise BridgeError("pairing file is malformed")
    return pairing

# -------------------- inlined: flslacker/fl_src/midi_main.py --------------------

"""FL Slacker MIDI metadata adapter (optional, read-only).

Assign this controller script to a dedicated MIDI input (for example a loopMIDI port).
It never edits the project. From OnIdle it periodically writes a small signed status
message (tempo, transport, channel/pattern/mixer names) and reports project loads so
the companion can invalidate its session. All host calls go through a literal,
version-gated allowlist; nothing is dispatched by caller-supplied name.
"""

import os
import time


import channels
import general
import mixer
import patterns
import transport
import ui

SLACKER_MIDI_VERSION = "0.1.0"
STATUS_INTERVAL_SECONDS = 2.0
NAMES_INTERVAL_SECONDS = 10.0
HEARTBEAT_SECONDS = 30.0
NAME_LIMIT = 128
PL_LOAD_OK = 100


def _api_version():
    try:
        return int(general.getVersion())
    except Exception:
        return 0


def _call(minimum_api, function, *args):
    """Call an allowlisted host function if the API version supports it."""
    if _state["api"] < minimum_api:
        return None
    try:
        return function(*args)
    except Exception:
        return None


def _names(count_function, name_function, first, api_needed):
    count = _call(api_needed, count_function)
    if not isinstance(count, int):
        return None
    items = []
    for index in range(first, min(count, NAME_LIMIT) + first):
        items.append(_call(api_needed, name_function, index))
    return {"index_origin": first, "count": count, "names": items, "truncated": count > NAME_LIMIT}


_state = {
    "api": 0,
    "last_status": 0.0,
    "last_names": 0.0,
    "last_sent": 0.0,
    "last_hash": None,
    "names": None,
    "pairing_mtime": None,
    "pairing": None,
}


def _pairing():
    path = pairing_path(base_dir())
    try:
        mtime = os.path.getmtime(path)
    except OSError:
        _state["pairing"] = None
        return None
    if mtime != _state["pairing_mtime"]:
        _state["pairing_mtime"] = mtime
        try:
            _state["pairing"] = read_pairing(base_dir())
        except BridgeError:
            _state["pairing"] = None
    return _state["pairing"]


def _send(body):
    pairing = _pairing()
    if pairing is None:
        return False
    try:
        folder = os.path.join(session_path(base_dir(), pairing["session_id"]), "responses")
        if not os.path.isdir(folder):
            return False
        envelope = make_envelope(
            pairing["secret"], "midi_status", pairing["session_id"], time.time_ns(), body, 300
        )
        atomic_write_text(folder, str(uuid.uuid4()) + ".json", canonical_dumps(envelope))
        return True
    except Exception:
        return False


def _status(event):
    now = time.monotonic()
    if _state["names"] is None or now - _state["last_names"] >= NAMES_INTERVAL_SECONDS:
        _state["last_names"] = now
        _state["names"] = {
            "channels": _names(channels.channelCount, channels.getChannelName, 0, 1),
            "patterns": _names(patterns.patternCount, patterns.getPatternName, 1, 1),
            "mixer_tracks": _names(mixer.trackCount, mixer.getTrackName, 0, 1),
        }
    return {
        "event": event,
        "adapter_version": SLACKER_MIDI_VERSION,
        "api_version": _state["api"],
        "safe_to_edit": _call(29, general.safeToEdit),
        "tempo_bpm": _call(38, mixer.getCurrentTempo, 0),
        "playing": _call(1, transport.isPlaying),
        "recording": _call(1, transport.isRecording),
        "current_pattern": _call(1, patterns.patternNumber),
        "selected_channel": _call(5, channels.selectedChannel, 1, 0, 1),
        "title": _call(1, ui.getProgTitle),
        "undo_history_count": _call(1, general.getUndoHistoryCount),
        "names": _state["names"],
    }


def OnInit():
    _state["api"] = _api_version()
    status = _status("adapter_started")
    if _send(status):
        now = time.monotonic()
        _state["last_status"] = _state["last_sent"] = now
        status["event"] = "status"
        _state["last_hash"] = sha256_hex(status)


def OnDeInit():
    _send({"event": "adapter_stopped", "adapter_version": SLACKER_MIDI_VERSION})


def OnIdle():
    now = time.monotonic()
    if now - _state["last_status"] < STATUS_INTERVAL_SECONDS:
        return
    _state["last_status"] = now
    status = _status("status")
    digest = sha256_hex(status)
    if digest == _state["last_hash"] and now - _state["last_sent"] < HEARTBEAT_SECONDS:
        return
    if _send(status):
        _state["last_hash"] = digest
        _state["last_sent"] = now


def OnProjectLoad(status):
    if status == PL_LOAD_OK or status == 0:
        _state["names"] = None
        _send({"event": "project_load", "load_status": int(status), "adapter_version": SLACKER_MIDI_VERSION})
