"""Render the self-contained FL-side scripts from the stdlib-only sources.

FL's embedded interpreter cannot import the companion package, so each script is
the concatenation of ``contracts/canonical.py``, ``contracts/wire.py`` and the
FL-side sources, with lines marked ``# fl-inline: skip`` removed.
"""

from __future__ import annotations

from dataclasses import dataclass
from importlib import resources
from pathlib import Path

from flslacker import __version__

SKIP_MARKER = "# fl-inline: skip"


@dataclass(frozen=True)
class FlScript:
    filename: str
    kind: str  # "piano_roll" | "midi"
    modules: tuple[str, ...]
    summary: str
    dev_only: bool = False


PIANO_ROLL_BASE = ("contracts/canonical.py", "contracts/wire.py", "fl_src/fl_common.py")

SCRIPTS: tuple[FlScript, ...] = (
    FlScript(
        "Slacker Capture.pyscript",
        "piano_roll",
        PIANO_ROLL_BASE + ("fl_src/capture_main.py",),
        "Records the notes FL exposes to this script as a signed snapshot. Never edits.",
    ),
    FlScript(
        "Slacker Apply.pyscript",
        "piano_roll",
        PIANO_ROLL_BASE + ("fl_src/apply_main.py",),
        "Applies one reviewed, signed FL Slacker plan after confirming the target.",
    ),
    FlScript(
        "Slacker Probe.pyscript",
        "piano_roll",
        PIANO_ROLL_BASE + ("fl_src/probe_main.py",),
        "Read-only compatibility probe for `flslacker doctor`.",
    ),
    FlScript(
        "Slacker M0 Mutation Probe.pyscript",
        "piano_roll",
        PIANO_ROLL_BASE + ("fl_src/m0_mutation_main.py",),
        "Developer probe for disposable projects: records how writes behave.",
        dev_only=True,
    ),
    FlScript(
        "device_Slacker.py",
        "midi",
        ("contracts/canonical.py", "contracts/wire.py", "fl_src/midi_main.py"),
        "Optional read-only MIDI metadata adapter.",
    ),
)


def _source(relative: str) -> str:
    return resources.files("flslacker").joinpath(relative).read_text(encoding="utf-8")


def render(script: FlScript) -> str:
    title = script.filename.rsplit(".", 1)[0]
    lines: list[str] = []
    if script.kind == "midi":
        lines += ["# name=FL Slacker (metadata)", "# url=", ""]
    lines += [
        '"""%s - FL Slacker adapter (protocol flslacker/1, package %s).' % (title, __version__),
        "",
        script.summary,
        "",
        "GENERATED by `flslacker build-fl-scripts` from src/flslacker; do not edit by hand.",
        '"""',
        "",
    ]
    if script.kind == "piano_roll":
        lines += ["import flpianoroll as flp", ""]
    for relative in script.modules:
        lines += ["", "# " + "-" * 20 + " inlined: flslacker/" + relative + " " + "-" * 20, ""]
        for line in _source(relative).splitlines():
            if line.rstrip().endswith(SKIP_MARKER):
                continue
            lines.append(line.rstrip())
    text = "\n".join(lines).rstrip() + "\n"
    compile(text, script.filename, "exec")
    return text


def render_all(include_dev: bool = True) -> dict[str, str]:
    return {s.filename: render(s) for s in SCRIPTS if include_dev or not s.dev_only}


def write_all(destination: Path, include_dev: bool = True) -> list[Path]:
    destination.mkdir(parents=True, exist_ok=True)
    written = []
    for name, text in render_all(include_dev).items():
        path = destination / name
        path.write_text(text, encoding="utf-8", newline="\n")
        written.append(path)
    return written


def script(filename: str) -> FlScript:
    for item in SCRIPTS:
        if item.filename == filename:
            return item
    raise KeyError(filename)
