"""Install or remove only the FL-side files FL Slacker owns.

Files go under the user's FL data folder, in ``Settings/Piano roll scripts/Slacker/`` and
(optionally) ``Settings/Hardware/Slacker/``. A manifest records what was written. Existing
files that FL Slacker did not write are never overwritten, and MIDI settings are never
changed: the user selects the controller script in FL's MIDI settings.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path

from flslacker import __version__, fl_build

MANIFEST = ".flslacker-manifest.json"
GENERATED_MARKER = "GENERATED by `flslacker build-fl-scripts`"


@dataclass
class InstallItem:
    path: Path
    content: str
    action: str  # create | update | unchanged | conflict
    reason: str = ""


def _sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def target_dirs(fl_user_dir: Path) -> dict[str, Path]:
    settings = Path(fl_user_dir) / "Settings"
    return {
        "piano_roll": settings / "Piano roll scripts" / "Slacker",
        "midi": settings / "Hardware" / "Slacker",
    }


def _manifest(folder: Path) -> dict[str, str]:
    path = folder / MANIFEST
    if not path.exists():
        return {}
    try:
        return dict(json.loads(path.read_text(encoding="utf-8")).get("files", {}))
    except (ValueError, OSError):
        return {}


def validate_fl_user_dir(fl_user_dir: Path) -> None:
    if not (Path(fl_user_dir) / "Settings").is_dir():
        raise ValueError(
            f"{fl_user_dir} does not look like an FL Studio user data folder (no Settings folder). "
            "Check FL's Options > File settings > User data folder."
        )


def plan(fl_user_dir: Path, include_midi: bool = False, include_dev: bool = False, force: bool = False) -> list[InstallItem]:
    validate_fl_user_dir(fl_user_dir)
    dirs = target_dirs(fl_user_dir)
    items = []
    for script in fl_build.SCRIPTS:
        if script.dev_only and not include_dev:
            continue
        if script.kind == "midi" and not include_midi:
            continue
        folder = dirs["midi" if script.kind == "midi" else "piano_roll"]
        path = folder / script.filename
        content = fl_build.render(script)
        owned = _manifest(folder)
        if not path.exists():
            items.append(InstallItem(path, content, "create"))
            continue
        current = path.read_text(encoding="utf-8", errors="replace")
        if current == content:
            items.append(InstallItem(path, content, "unchanged"))
        elif owned.get(path.name) == _sha(current) or (path.name not in owned and GENERATED_MARKER in current):
            items.append(InstallItem(path, content, "update"))
        elif force and (path.name in owned or GENERATED_MARKER in current):
            items.append(InstallItem(path, content, "update", "local changes will be overwritten (--force)"))
        else:
            reason = "modified since installation" if path.name in owned else "not written by FL Slacker"
            items.append(InstallItem(path, content, "conflict", reason))
    return items


def apply(items: list[InstallItem]) -> None:
    if any(item.action == "conflict" for item in items):
        raise RuntimeError("Refusing to install: resolve the conflicts first.")
    by_folder: dict[Path, list[InstallItem]] = {}
    for item in items:
        by_folder.setdefault(item.path.parent, []).append(item)
    for folder, group in by_folder.items():
        folder.mkdir(parents=True, exist_ok=True)
        files = _manifest(folder)
        for item in group:
            if item.action in ("create", "update"):
                item.path.write_text(item.content, encoding="utf-8", newline="\n")
            files[item.path.name] = _sha(item.content)
        (folder / MANIFEST).write_text(
            json.dumps({"owner": "flslacker", "version": __version__, "files": files}, indent=2),
            encoding="utf-8",
        )


def uninstall_plan(fl_user_dir: Path, force: bool = False) -> list[tuple[Path, str]]:
    """(path, action) where action is 'remove' or 'keep: <reason>'."""
    result = []
    for folder in target_dirs(fl_user_dir).values():
        owned = _manifest(folder)
        for name, digest in sorted(owned.items()):
            path = folder / name
            if not path.exists():
                continue
            current = path.read_text(encoding="utf-8", errors="replace")
            if _sha(current) == digest or force:
                result.append((path, "remove"))
            else:
                result.append((path, "keep: modified since installation (use --force)"))
    return result


def uninstall(fl_user_dir: Path, force: bool = False) -> list[Path]:
    removed = []
    for path, action in uninstall_plan(fl_user_dir, force):
        if action == "remove":
            path.unlink()
            removed.append(path)
    for folder in target_dirs(fl_user_dir).values():
        manifest = folder / MANIFEST
        remaining = {p.name for p in folder.iterdir()} - {MANIFEST} if folder.is_dir() else set()
        if manifest.exists():
            files = {k: v for k, v in _manifest(folder).items() if k in remaining}
            if files:
                manifest.write_text(json.dumps({"owner": "flslacker", "version": __version__, "files": files},
                                               indent=2), encoding="utf-8")
            else:
                manifest.unlink()
        if folder.is_dir() and not any(folder.iterdir()):
            folder.rmdir()
    return removed


def status(fl_user_dir: Path) -> dict[str, str]:
    """filename -> installed state, for doctor."""
    out = {}
    try:
        items = plan(fl_user_dir, include_midi=True, include_dev=True)
    except ValueError as exc:
        return {"error": str(exc)}
    for item in items:
        name = item.path.name
        if item.action == "create":
            out[name] = "not installed"
        elif item.action == "unchanged":
            out[name] = "installed, current"
        elif item.action == "update":
            out[name] = "installed, outdated (run install-adapters)"
        else:
            out[name] = f"conflict: {item.reason}"
    return out
